version: '3.7'
services:

  app:
    build:
      context: ./app
      dockerfile: dockerfile-prod
    depends_on:
      - database
      - etlpipeline
    environment:
      - flask_env=prod
    command: python3 main.py
    volumes:
    - ./app/:/app/
    ports:
    - 8010:80
    
  database:
    image: "mongo:4.2"
    expose:
    - 27017
    volumes:
    - ./database/mongo:/data/db
    
  etlpipeline:
    depends_on:
      - database
    build:
      context: ./etl
      dockerfile: dockerfile
    volumes:
    - ./data/:/data/
    - ./etl/:/app/

    
  
